/* File: src/components/CreateDocumentModal.jsx
 * ARCHITECTURE (Layered): React UI -> api service -> monolith service chain.
 * ARCHITECTURE (Event-Driven): same UI contract; write calls trigger domain events.
 * Service communication: Context + API + WebSocket.
 * Events/Methods: REST methods in layered, event publication/consumption in EDA.
 */
import { useState } from 'react'
import { createDocument } from '../services/api'
export default function CreateDocumentModal({isOpen,onClose,onCreated}){const [title,setTitle]=useState(''); const [content,setContent]=useState(''); const [visibility,setVisibility]=useState('private'); const [ok,setOk]=useState(false); if(!isOpen) return null; const submit=async()=>{if(!title.trim())return; await createDocument(title,content,visibility); onCreated?.(); setOk(true); setTimeout(()=>{setOk(false); onClose?.()},1500)}; return <div className='fixed inset-0 z-50 flex items-center justify-center bg-black/40'><div className='w-full max-w-lg rounded-modal bg-white p-6'><div className='mb-4 flex items-center justify-between'><h3 className='text-xl font-bold'>Create New Document</h3><span className='rounded-full bg-editor-bg px-3 py-1 text-xs text-editor-text'>Unique Doc ID auto-assigned on creation</span></div><label className='text-[13px] font-medium'>Document Title</label><input className='mt-1 h-10 w-full rounded-button border border-border px-3' placeholder='Enter a title...' value={title} onChange={(e)=>setTitle(e.target.value)}/><label className='mt-3 block text-[13px] font-medium'>Initial Content (optional)</label><textarea rows={4} className='mt-1 w-full rounded-button border border-border p-3' value={content} onChange={(e)=>setContent(e.target.value)}/><label className='mt-3 block text-[13px] font-medium'>Visibility</label><div className='mt-1 flex gap-4 text-sm'><label><input type='radio' checked={visibility==='private'} onChange={()=>setVisibility('private')}/> Private (only me)</label><label><input type='radio' checked={visibility==='shared'} onChange={()=>setVisibility('shared')}/> Shared (invite others)</label></div><div className='mt-5 flex justify-end gap-2'>{ok?<div className='text-sm font-medium text-success'>✓ Document created successfully</div>:<><button className='h-10 rounded-button border border-border px-4' onClick={onClose}>Cancel</button><button className='h-10 rounded-button bg-primary px-4 text-white' onClick={submit}>Create Document</button></>}</div></div></div> }
