/* File: src/components/ShareDocumentModal.jsx
 * ARCHITECTURE (Layered): React UI -> api service -> monolith service chain.
 * ARCHITECTURE (Event-Driven): same UI contract; write calls trigger domain events.
 * Service communication: Context + API + WebSocket.
 * Events/Methods: REST methods in layered, event publication/consumption in EDA.
 */
import { useEffect,useMemo,useState } from 'react'
import { searchUsers,shareDocument } from '../services/api'
import Avatar from './Avatar'
import Badge from './Badge'
export default function ShareDocumentModal({documentId,documentTitle,collaborators=[],isOpen,onClose}){const [query,setQuery]=useState(''); const [results,setResults]=useState([]); const [pending,setPending]=useState([]); const [linkSharing,setLinkSharing]=useState('disabled'); useEffect(()=>{if(!query.trim()){setResults([]);return} const t=setTimeout(async()=>{const r=await searchUsers(query); setResults(r.data||[])},300); return ()=>clearTimeout(t)},[query]); if(!isOpen) return null; const list=useMemo(()=>[...collaborators,...pending],[collaborators,pending]); const send=async()=>{await shareDocument(documentId,{invitees:pending.map((u)=>({userId:u.id,role:'editor'})),linkSharing}); onClose?.()}; return <div className='fixed inset-0 z-50 flex items-center justify-center bg-black/40'><div className='w-full max-w-xl rounded-modal bg-white p-6'><h3 className='text-xl font-bold'>Share — '{documentTitle}'</h3><p className='mt-2 inline-block rounded-full bg-editor-bg px-3 py-1 text-xs text-editor-text'>Only registered users can be invited</p><label className='mt-4 block text-[13px] font-medium'>Invite by username or email</label><input className='mt-1 h-10 w-full rounded-button border border-border px-3' value={query} onChange={(e)=>setQuery(e.target.value)}/>{results.length>0?<div className='mt-1 max-h-36 overflow-y-auto rounded-button border border-border'>{results.map((u)=><button key={u.id} className='flex w-full items-center gap-2 px-3 py-2 hover:bg-background' onClick={()=>setPending((p)=>p.some((x)=>x.id===u.id)?p:[...p,u])}><Avatar name={u.username}/><span>{u.username}</span></button>)}</div>:null}<h4 className='mt-4 text-sm font-semibold'>Current Collaborators</h4><div className='mt-2 space-y-2'>{list.map((c,i)=><div key={`${c.id}-${i}`} className='flex items-center justify-between rounded-button border border-border p-2'><div className='flex items-center gap-2'><Avatar name={c.username||c.name}/><span className='text-sm'>{c.username||c.name}</span></div><Badge type={i===0?'owner':'editor'}/></div>)}</div><h4 className='mt-4 text-sm font-semibold'>Link Sharing</h4><div className='mt-2 grid grid-cols-3 gap-2'>{['disabled','view only','can edit'].map((v)=><button key={v} className={`h-9 rounded-button border text-sm ${linkSharing===v?'border-primary bg-primary text-white':'border-border'}`} onClick={()=>setLinkSharing(v)}>{v}</button>)}</div><button className='mt-5 h-[42px] w-full rounded-button bg-primary text-white' onClick={send}>Send Invitations</button></div></div> }
