/* File: src/pages/NotificationsPage.jsx
 * ARCHITECTURE (Layered): React UI -> api service -> monolith service chain.
 * ARCHITECTURE (Event-Driven): same UI contract; write calls trigger domain events.
 * Service communication: Context + API + WebSocket.
 * Events/Methods: REST methods in layered, event publication/consumption in EDA.
 */
import { useEffect,useMemo,useState } from 'react'
import { BellIcon,PencilSquareIcon,ArrowPathIcon,UserGroupIcon } from '@heroicons/react/24/outline'
import Navbar from '../components/Navbar'
import { getNotifications,markAllRead } from '../services/api'
import socketService from '../services/socket'
import { useAuth } from '../contexts/AuthContext'
export default function NotificationsPage(){const {user,token,logout}=useAuth(); const [notifications,setNotifications]=useState([]); const [filter,setFilter]=useState('all'); const [loading,setLoading]=useState(true); useEffect(()=>{(async()=>{const r=await getNotifications(); setNotifications(r.data||[]); setLoading(false)})()},[]); useEffect(()=>{socketService.connect(token); socketService.onNotification((n)=>setNotifications((p)=>[n,...p])); return ()=>socketService.disconnect()},[token]); const shown=useMemo(()=>filter==='all'?notifications:notifications.filter((n)=>n.type===filter.slice(0,-1)),[notifications,filter]); const icon=(t)=>t==='share'?<UserGroupIcon className='h-4 w-4'/>:t==='edit'?<PencilSquareIcon className='h-4 w-4'/>:<ArrowPathIcon className='h-4 w-4'/>; const bg=(t)=>t==='share'?'bg-owner-bg text-owner-text':t==='edit'?'bg-shared-bg text-shared-text':'bg-editor-bg text-editor-text'; return <div><Navbar currentPage='notifications' username={user?.username} onLogout={logout} notifCount={notifications.filter((n)=>!n.read).length}/><div className='mx-auto max-w-app p-6'><div className='mb-4 flex items-center justify-between'><h1 className='text-2xl font-bold'>Notifications</h1><button className='h-9 rounded-button border border-border px-3 text-sm' onClick={async()=>{await markAllRead(); setNotifications((p)=>p.map((n)=>({...n,read:true})))}}>Mark all as read</button></div><div className='mb-3 flex border-b border-border'>{['all','shares','edits','restores'].map((t)=><button key={t} className={`-mb-px mr-4 border-b-2 pb-2 text-sm font-medium ${filter===t?'border-primary text-primary':'border-transparent text-text-secondary'}`} onClick={()=>setFilter(t)}>{t[0].toUpperCase()+t.slice(1)}</button>)}</div>{loading?<div className='py-10 text-center text-text-secondary'><BellIcon className='mx-auto h-6 w-6'/> Loading...</div>:<div>{shown.map((n)=><div key={n.id} className='flex min-h-12 items-center justify-between border-b border-border px-1 py-3 hover:bg-background'><div className='flex items-center gap-3'><div className={`flex h-7 w-7 items-center justify-center rounded-full ${bg(n.type)}`}>{icon(n.type)}</div><div><p className='text-sm'>{n.actor} {n.type==='share'?'shared':n.type==='edit'?'edited':'restored'} {n.documentTitle}</p><p className='text-xs text-muted'>{n.relativeTime||'just now'}</p></div></div>{!n.read?<span className='h-2 w-2 rounded-full bg-primary'/>:null}</div>)}</div>}</div></div> }
