/* File: src/pages/VersionHistoryPage.jsx
 * ARCHITECTURE (Layered): React UI -> api service -> monolith service chain.
 * ARCHITECTURE (Event-Driven): same UI contract; write calls trigger domain events.
 * Service communication: Context + API + WebSocket.
 * Events/Methods: REST methods in layered, event publication/consumption in EDA.
 */
import { useEffect,useMemo,useState } from 'react'
import { useNavigate,useParams } from 'react-router-dom'
import Navbar from '../components/Navbar'
import RestoreVersionModal from '../components/RestoreVersionModal'
import { getDocument,getRevisions } from '../services/api'
import { useAuth } from '../contexts/AuthContext'
export default function VersionHistoryPage(){const {id}=useParams(); const {user,logout}=useAuth(); const [documentTitle,setDocumentTitle]=useState(''); const [revisions,setRevisions]=useState([]); const [chrono,setChrono]=useState(false); const [selected,setSelected]=useState(null); const navigate=useNavigate(); const load=async()=>{const [d,r]=await Promise.all([getDocument(id),getRevisions(id)]); setDocumentTitle(d.data?.title||''); setRevisions(r.data||[])}; useEffect(()=>{load()},[id]); const list=useMemo(()=>chrono?[...revisions].reverse():revisions,[revisions,chrono]); return <div><Navbar currentPage='documents' username={user?.username} onLogout={logout}/><div className='mx-auto max-w-app p-6'><div className='mb-6 flex items-center justify-between'><h1 className='text-2xl font-bold'>Version History — '{documentTitle}'</h1><button className='rounded-full border border-border px-3 py-1 text-sm' onClick={()=>setChrono((c)=>!c)}>{chrono?'Newest first':'Chronological · newest first'}</button></div><div className='space-y-4'>{list.map((r,idx)=><div key={r.id} className='flex gap-3'><div className='flex w-6 flex-col items-center'><div className={`h-3 w-3 rounded-full ${r.current?'bg-primary':'bg-border'}`}/>{idx!==list.length-1?<div className='mt-1 h-full w-px bg-border'/>:null}</div><div className='flex-1 rounded-card border border-border bg-white p-4'><div className='flex items-center justify-between'><div className='text-sm font-semibold'>v{r.version} {r.current?'(Current)':''}</div>{r.current?<span className='rounded-full bg-green-100 px-2 py-0.5 text-xs text-green-700'>Current</span>:<button className='rounded-button border border-border px-3 py-1 text-sm' onClick={()=>setSelected(r)}>Restore</button>}</div><p className='mt-1 text-[13px] text-text-secondary'>{r.username} · {new Date(r.createdAt).toLocaleString()}</p><p className='mt-2 text-sm'>{r.change}</p></div></div>)}</div><button className='mt-5 text-sm text-primary' onClick={()=>navigate(`/documents/${id}`)}>← Back to editor</button></div><RestoreVersionModal isOpen={!!selected} onClose={()=>setSelected(null)} documentId={id} documentTitle={documentTitle} selectedVersion={selected} currentVersion={revisions.find((x)=>x.current)} onRestored={()=>navigate(`/documents/${id}`)}/></div> }
